Added example files

diff --git a/bin/build_zorg_grammars b/bin/build_zorg_grammars
--- a/bin/build_zorg_grammars
+++ b/bin/build_zorg_grammars
@@ -1,3 +1,33 @@
 #!/bin/bash
 
-antlr4 -Dlanguage=Python3 src/zorg/grammar/zorg_file/ZorgFile.g4
+readonly BIN="$(dirname "$0")"
+readonly ROOT="$(dirname "${BIN}")"
+
+source "${ROOT}"/lib/bugyi.sh
+
+set -e
+
+TMPFILE="$(mktemp -t --suffix=.SUFFIX build_zorg_grammars.XXXXXX)"
+trap "rm -f '$TMPFILE'" 0               # EXIT
+trap "rm -f '$TMPFILE'; exit 1" 2       # INT
+trap "rm -f '$TMPFILE'; exit 1" 1 15    # HUP TERM
+
+function run() {
+    for dir in "zorg_file"; do
+      log::info "Generating %s parser using antlr4." $dir
+      antlr4 -Dlanguage=Python3 src/zorg/grammar/$dir/*.g4
+      for f in examples/$dir/*.zo; do
+        log::info "Parsing tokens and contructing syntax tree from %s example file." $f
+        antlr4-parse src/zorg/grammar/$dir/*.g4 prog -tokens -tree $f 2>> $TMPFILE
+      done
+
+      if [ -s $TMPFILE ]; then
+        log::error "Errors were logged while parsing some of the example files."
+        return 1
+      fi
+    done
+}
+
+if [[ "${SCRIPTNAME}" == "$(basename "${BASH_SOURCE[0]}")" ]]; then
+    run "$@"
+fi
